GET http://localhost:3000/conclusions

###

POST http://localhost:3000/conclusions/add
Content-Type: application/json

{
  "colors": ["yellow", "red", "green", "blue"],
  "ids":[ ["1", "2", "3", "4"] ]
}
